# Generated by Django 4.2.28 on 2026-03-13

from django.db import migrations


def migrate_backlog_state_to_validation(apps, schema_editor):
    State = apps.get_model("db", "State")

    backlog_states = State.objects.filter(group="backlog", deleted_at__isnull=True)
    for state in backlog_states.iterator():
        updates = {}

        if state.color != "#0693E3":
            updates["color"] = "#0693E3"

        if state.default and (state.sequence is None or state.sequence < 30000):
            updates["sequence"] = 30000

        if state.name == "Backlog":
            duplicate_exists = (
                State.objects.filter(project_id=state.project_id, name="In Review", deleted_at__isnull=True)
                .exclude(id=state.id)
                .exists()
            )
            if not duplicate_exists:
                updates["name"] = "In Review"

        if updates:
            State.objects.filter(id=state.id).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0120_issueview_archived_at"),
    ]

    operations = [
        migrations.RunPython(migrate_backlog_state_to_validation, migrations.RunPython.noop),
    ]
