# Generated by Django 4.2.29 on 2026-03-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_imt_cancelled_state_color_red'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ica_html',
            field=models.TextField(blank=True, default='<p></p>'),
        ),
        migrations.AddField(
            model_name='issue',
            name='pca_html',
            field=models.TextField(blank=True, default='<p></p>'),
        ),
        migrations.AddField(
            model_name='issue',
            name='rca_html',
            field=models.TextField(blank=True, default='<p></p>'),
        ),
        migrations.AlterField(
            model_name='state',
            name='group',
            field=models.CharField(choices=[('backlog', 'Validation'), ('unstarted', 'Unstarted'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('triage', 'Triage')], default='backlog', max_length=20),
        ),
    ]
